apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.service }}
spec:
  selector:
    app: {{ .Values.name.container }}
  ports:
    - protocol: TCP
      # Service 在 Kubernetes 集群内部暴露的端口
      port: {{ .Values.service.port }}
      # pod 内部 MySQL 进程监听的端口
      targetPort: {{ .Values.service.port }}
  type: ClusterIP