# 如果 values.yaml 中 serviceAccount.create 为 true，才会生成这个 ServiceAccount。
{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
# 是否自动把 ServiceAccount 的 token 挂载到 Pod 内。
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  # ServiceAccount 的名字由 Helm 的 模板函数 jenkins.serviceAccountName 生成。
  name: {{ include "jenkins.serviceAccountName" . }}
  # 指定 ServiceAccount 的 namespace，由 Helm 模板函数生成（通常是 default 或者你自己在 values.yaml 指定的 namespace）。
  namespace: {{ template "jenkins.namespace" . }}
# 如果 values.yaml 里有指定 annotations，就把它们写入 metadata.annotations，tpl 可以解析字符串模板，toYaml 把 YAML 对象转换成字符串，indent 4 缩进四格。
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml .Values.serviceAccount.annotations) . | indent 4 }}
{{- end }}
# 给 ServiceAccount 添加 labels，使用 jenkins.labels 模板函数生成标签。
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
# 如果有 extraLabels，也会加到 labels 里。
{{- if .Values.serviceAccount.extraLabels }}
{{ tpl (toYaml .Values.serviceAccount.extraLabels) . | indent 4 }}
{{- end }}
# 如果你在 values.yaml 里指定了 imagePullSecretName，Helm 会把它挂载到 ServiceAccount 上。这样通过这个 ServiceAccount 创建的 Pod 就可以自动使用这个 secret 拉取私有镜像。
{{- if .Values.serviceAccount.imagePullSecretName }}
imagePullSecrets:
  - name: {{ .Values.serviceAccount.imagePullSecretName }}
{{- end -}}
{{ end }}
